AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Back-end service for the Momento Pizza App

Parameters:  
  MomentoApiToken:
    Type: String
    Description: API token for Momento Cache
    NoEcho: true
    Default: ''  

Globals:
  Function:
    Runtime: nodejs18.x 
    Architectures:
      - arm64
    Tracing: Active
    Timeout: 3
    MemorySize: 1024
    Handler: index.handler
    Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:094274105915:layer:AWSLambdaPowertoolsTypeScript:12
      - !Ref DependencyLayer
    Environment:
      Variables:
        AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
        SECRET_ID: !Ref MomentoSecret
  Api:
    Cors:
      AllowMethods: "'POST,GET,PUT,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  OrderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./order-openapi.yaml

  AdminApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./admin-openapi.yaml

  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: nodejs18.x
    Properties:
      ContentUri: layers/
      CompatibleRuntimes:
        - nodejs18.x

  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST      
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: type
          AttributeType: S
        - AttributeName: creator
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: type
          KeySchema:
            - AttributeName: type
              KeyType: HASH
            - AttributeName: creator
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  MomentoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString:
        Fn::Sub:
          - |-
            {            
              "momento": "${MomentoApiToken}"
            }
          - MomentoApiToken: !Ref MomentoApiToken

  # Order Api Functions
  AddOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/add-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:BatchWriteItem
              Resource: !GetAtt OrderTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApi
            Path: /orders
            Method: POST

  GetMyOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-my-orders
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !Sub ${OrderTable.Arn}/index/type
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApi
            Path: /orders
            Method: GET

  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !GetAtt OrderTable.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
          RESTRICT_TO_CREATOR: true
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApi
            Path: /orders/{orderId}
            Method: GET

  UpdateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - dynamodb:UpdateItem
                - dynamodb:BatchWriteItem
              Resource: !GetAtt OrderTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApi
            Path: /orders/{orderId}
            Method: PUT

  SubmitOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/submit-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !GetAtt OrderTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref OrderApi
            Path: /orders/{orderId}/statuses
            Method: POST

  # Admin Api Functions
  GetAllOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-all-orders
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !Sub ${OrderTable.Arn}/index/type
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref AdminApi
            Path: /orders
            Method: GET

  UpdateOrderStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/update-order-status
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - dynamodb:UpdateItem
                - dynamodb:GetItem
              Resource: !GetAtt OrderTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref AdminApi
            Path: /orders/{orderId}/statuses
            Method: POST
        
  AdminGetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: dynamodb:Query
              Resource: !GetAtt OrderTable.Arn
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref MomentoSecret
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
          RESTRICT_TO_CREATOR: false
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref AdminApi
            Path: /orders/{orderId}
            Method: GET

  # Load Generator
  DeleteOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: load-generator/functions/delete-order
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: 
                - dynamodb:Query
                - dynamodb:BatchWriteItem
              Resource: !GetAtt OrderTable.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref OrderTable
  
  GenerateOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: load-generator/functions/generate-orders
      Policies:
        - AWSLambdaBasicExecutionRole

  SendRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: load-generator/functions/send-request
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole

  GeneratorStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      DefinitionUri: load-generator/workflows/generator.asl.json
      DefinitionSubstitutions:
        LambdaInvoke: !Sub arn:${AWS::Partition}:states:::lambda:invoke
        GenerateOrders: !GetAtt GenerateOrdersFunction.Arn
        SendRequest: !GetAtt SendRequestFunction.Arn
        DeleteOrder: !GetAtt DeleteOrderFunction.Arn
        OrderApiBaseUrl: !Sub https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/dev
        AdminApiBaseUrl: !Sub https://${AdminApi}.execute-api.${AWS::Region}.amazonaws.com/dev
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource:
                - !GetAtt GenerateOrdersFunction.Arn
                - !GetAtt SendRequestFunction.Arn
                - !GetAtt DeleteOrderFunction.Arn
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"  
      Events:
        StartEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - Load Generator
              source:
                - momento.pizza
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt GeneratorLogGroup.Arn

  GeneratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 30

  # Monitoring Dashboard
  LatencyDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: MomentoPizza
      DashboardBody: 
        Fn::Sub: 
          - |-
            {
                "widgets": [
                    {
                        "height": 12,
                        "width": 12,
                        "y": 6,
                        "x": 0,
                        "type": "metric",
                        "properties": {
                            "metrics": [
                                [ "Momento", "get-all-orders-latency-total", "service", "pizza-tracker", { "label": "get-all-orders-total", "region": "us-west-2" } ],
                                [ ".", "get-all-orders-latency-ddb", ".", ".", { "label": "get-all-orders-ddb", "region": "us-west-2" } ],
                                [ ".", "get-all-orders-latency-cache", ".", ".", { "label": "get-all-orders-cache", "region": "us-west-2" } ],
                                [ ".", "get-my-orders-latency-total", ".", ".", { "label": "get-my-orders-total", "region": "us-west-2" } ],
                                [ ".", "get-my-orders-latency-ddb", ".", ".", { "label": "get-my-orders-ddb", "region": "us-west-2" } ],
                                [ ".", "get-my-orders-latency-cache", ".", ".", { "label": "get-my-orders-cache", "region": "us-west-2" } ],
                                [ ".", "get-order-latency-total", ".", ".", { "region": "us-west-2", "label": "get-order-total" } ],
                                [ ".", "get-order-latency-ddb", ".", ".", { "region": "us-west-2", "label": "get-order-ddb" } ],
                                [ ".", "get-order-latency-cache", ".", ".", { "region": "us-west-2", "label": "get-order-cache" } ]
                            ],
                            "view": "timeSeries",
                            "stacked": false,
                            "region": "us-west-2",
                            "stat": "Average",
                            "period": 60,
                            "title": "Avg Latency"
                        }
                    },
                    {
                        "height": 6,
                        "width": 12,
                        "y": 0,
                        "x": 12,
                        "type": "metric",
                        "properties": {
                            "metrics": [
                                [ "Momento", "get-all-orders-latency-total", "service", "pizza-tracker", { "region": "us-west-2", "label": "get-all-orders-total Avg" } ],
                                [ ".", "get-all-orders-latency-ddb", ".", ".", { "region": "us-west-2", "label": "get-all-orders-ddb Avg" } ],
                                [ ".", "get-all-orders-latency-cache", ".", ".", { "region": "us-west-2", "label": "get-all-orders-cache Avg" } ],
                                [ ".", "get-all-orders-latency-total", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-all-orders-total p99", "color": "#1f77b4" } ],
                                [ ".", "get-all-orders-latency-ddb", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-all-orders-ddb p99", "color": "#ff7f0e" } ],
                                [ ".", "get-all-orders-latency-cache", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-all-orders-cache p99", "color": "#2ca02c" } ]
                                ],
                            "sparkline": true,
                            "view": "singleValue",
                            "region": "us-west-2",
                            "title": "GetAllOrders Latency",
                            "period": 300,
                            "stat": "Average"
                        }
                    },
                    {
                        "height": 6,
                        "width": 12,
                        "y": 6,
                        "x": 12,
                        "type": "metric",
                        "properties": {
                            "metrics": [
                                [ "Momento", "get-my-orders-latency-total", "service", "pizza-tracker", { "region": "us-west-2", "label": "get-my-orders-total Avg", "color": "#d62728" } ],
                                [ ".", "get-my-orders-latency-ddb", ".", ".", { "region": "us-west-2", "label": "get-my-orders-ddb Avg", "color": "#9467bd" } ],
                                [ ".", "get-my-orders-latency-cache", ".", ".", { "region": "us-west-2", "label": "get-my-orders-cache Avg", "color": "#8c564b" } ],
                                [ ".", "get-my-orders-latency-total", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-my-orders-total p99" } ],
                                [ ".", "get-my-orders-latency-ddb", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-my-orders-ddb p99" } ],
                                [ ".", "get-my-orders-latency-cache", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-my-orders-cache p99" } ]
                            ],
                            "sparkline": true,
                            "view": "singleValue",
                            "region": "us-west-2",
                            "title": "GetMyOrders Latency",
                            "period": 300,
                            "stat": "Average"
                        }
                    },
                    {
                        "height": 6,
                        "width": 12,
                        "y": 12,
                        "x": 12,
                        "type": "metric",
                        "properties": {
                            "metrics": [
                                [ "Momento", "get-order-latency-total", "service", "pizza-tracker", { "region": "us-west-2", "label": "get-order-total Avg", "color": "#e377c2" } ],
                                [ ".", "get-order-latency-ddb", ".", ".", { "region": "us-west-2", "label": "get-order-ddb Avg", "color": "#7f7f7f" } ],
                                [ ".", "get-order-latency-cache", ".", ".", { "region": "us-west-2", "label": "get-order-cache Avg", "color": "#bcbd22" } ],
                                [ ".", "get-order-latency-total", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-order-total p99", "color": "#e377c2" } ],
                                [ ".", "get-order-latency-ddb", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-order-ddb p99", "color": "#7f7f7f" } ],
                                [ ".", "get-order-latency-cache", ".", ".", { "region": "us-west-2", "stat": "p99", "label": "get-order-cache p99", "color": "#bcbd22" } ]
                            ],
                            "sparkline": true,
                            "view": "singleValue",
                            "region": "us-west-2",
                            "title": "GetOrder Latency",
                            "period": 300,
                            "stat": "Average"
                        }
                    },
                    {
                        "height": 6,
                        "width": 12,
                        "y": 0,
                        "x": 0,
                        "type": "metric",
                        "properties": {
                            "metrics": [
                                [ "Momento", "get-order-cache-miss", "service", "pizza-tracker", { "region": "us-west-2" } ],
                                [ ".", "get-my-orders-cache-miss", ".", ".", { "region": "us-west-2" } ],
                                [ ".", "get-all-orders-cache-miss", ".", ".", { "region": "us-west-2" } ]
                            ],
                            "sparkline": true,
                            "view": "gauge",
                            "region": "us-west-2",
                            "title": "Cache Hit Rates",
                            "period": 300,
                            "stat": "p99",
                            "legend": {
                                "position": "bottom"
                            },
                            "yAxis": {
                                "left": {
                                    "min": 0,
                                    "max": 100
                                }
                            }
                        }
                    }
                ]
            }
          - region: !Ref AWS::Region

Outputs:
  OrderApiEndpoint:
    Description: Copy and paste this value in ./order-ui/next.config.js into the NEXT_PUBLIC_ORDER_API property
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
  AdminApiEndpoint:
    Description: Copy and paste this value in ./admin-ui/next.config.js into the NEXT_PUBLIC_ADMIN_API property
    Value: !Sub "https://${AdminApi}.execute-api.${AWS::Region}.amazonaws.com/dev"